/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisoriesRouteImport } from './routes/advisories'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as MapRouteImport } from './routes/map'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as OfficerAnalyticsRouteImport } from './routes/officer.analytics'
import { Route as OfficerMapRouteImport } from './routes/officer.map'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoriesRoute = AdvisoriesRouteImport.update({
  id: '/advisories',
  path: '/advisories',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/officer/',
  path: '/officer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerAnalyticsRoute = OfficerAnalyticsRouteImport.update({
  id: '/officer/analytics',
  path: '/officer/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerMapRoute = OfficerMapRouteImport.update({
  id: '/officer/map',
  path: '/officer/map',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisories': typeof AdvisoriesRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/locations': typeof LocationsRoute
  '/map': typeof MapRoute
  '/settings': typeof SettingsRoute
  '/officer/analytics': typeof OfficerAnalyticsRoute
  '/officer/map': typeof OfficerMapRoute
  '/officer/': typeof OfficerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisories': typeof AdvisoriesRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/locations': typeof LocationsRoute
  '/map': typeof MapRoute
  '/settings': typeof SettingsRoute
  '/officer/analytics': typeof OfficerAnalyticsRoute
  '/officer/map': typeof OfficerMapRoute
  '/officer': typeof OfficerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisories': typeof AdvisoriesRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/locations': typeof LocationsRoute
  '/map': typeof MapRoute
  '/settings': typeof SettingsRoute
  '/officer/analytics': typeof OfficerAnalyticsRoute
  '/officer/map': typeof OfficerMapRoute
  '/officer/': typeof OfficerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisories'
    | '/alerts'
    | '/dashboard'
    | '/forecast'
    | '/locations'
    | '/map'
    | '/settings'
    | '/officer/analytics'
    | '/officer/map'
    | '/officer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisories'
    | '/alerts'
    | '/dashboard'
    | '/forecast'
    | '/locations'
    | '/map'
    | '/settings'
    | '/officer/analytics'
    | '/officer/map'
    | '/officer'
  id:
    | '__root__'
    | '/'
    | '/advisories'
    | '/alerts'
    | '/dashboard'
    | '/forecast'
    | '/locations'
    | '/map'
    | '/settings'
    | '/officer/analytics'
    | '/officer/map'
    | '/officer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisoriesRoute: typeof AdvisoriesRoute
  AlertsRoute: typeof AlertsRoute
  DashboardRoute: typeof DashboardRoute
  ForecastRoute: typeof ForecastRoute
  LocationsRoute: typeof LocationsRoute
  MapRoute: typeof MapRoute
  SettingsRoute: typeof SettingsRoute
  OfficerAnalyticsRoute: typeof OfficerAnalyticsRoute
  OfficerMapRoute: typeof OfficerMapRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisories': {
      id: '/advisories'
      path: '/advisories'
      fullPath: '/advisories'
      preLoaderRoute: typeof AdvisoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/': {
      id: '/officer/'
      path: '/officer'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/analytics': {
      id: '/officer/analytics'
      path: '/officer/analytics'
      fullPath: '/officer/analytics'
      preLoaderRoute: typeof OfficerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/map': {
      id: '/officer/map'
      path: '/officer/map'
      fullPath: '/officer/map'
      preLoaderRoute: typeof OfficerMapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisoriesRoute: AdvisoriesRoute,
  AlertsRoute: AlertsRoute,
  DashboardRoute: DashboardRoute,
  ForecastRoute: ForecastRoute,
  LocationsRoute: LocationsRoute,
  MapRoute: MapRoute,
  SettingsRoute: SettingsRoute,
  OfficerAnalyticsRoute: OfficerAnalyticsRoute,
  OfficerMapRoute: OfficerMapRoute,
  OfficerIndexRoute: OfficerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
